name: biometrics_auth_poc
description: PoC - authorization with a fingerprint, faceId and pin code

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Architecure
  flutter_bloc: ^8.0.1

  # Biometrics
  local_auth: ^1.1.11

  # Code generation
  build_runner: ^2.1.8
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0

  # Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3
  injectable_generator: ^1.5.2

  # Test dependencies
  mockito: ^5.1.0
  bloc_test: ^9.0.2

  # Persistence
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
